# Generated by Django 5.0.2 on 2024-03-05 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stage',
            options={'verbose_name': ('Etapa',), 'verbose_name_plural': 'Etapas'},
        ),
    ]
